version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    user: 1000:1000
    volumes:
      - ./volumes/config:/config
      - ./volumes/cache:/cache
      - ./volumes/media:/media
      - ./volumes/media2:/media2:ro
      - truenas-share:/mnt/truenas/ # Media directory
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

#Mounts /mnt/transmission to transmission container
volumes:
  truenas-share: #Tied to volumes above
    driver: local
    driver_opts:
      type: cifs
      o: username=$dockerusername,password=$dockerpassword,rw
      device: "//10.10.10.12/share"
